const ROUTES = [
  { id: 1, title: "算法与增长", slug: "The cost of a better idea", tags: ["渐近分析", "复杂度", "模型"], summary: "算法不是一段能运行的代码，而是一个在规模增长时仍可讨论的过程。先写清输入、输出和资源模型，复杂度才有意义。", principles: [["01", "先定义规模", "n 代表什么要明确：元素数量、顶点数、位数，都会改变分析方式。"], ["02", "忽略低阶项", "渐近记号关心增长趋势，不关心特定机器上那一点常数差。"], ["03", "上界不是全部", "最坏、平均和最好情况回答不同问题；报告前先说清你在讨论哪一个。"]], steps: [["选量", "把输入规模 n 和基本操作说清楚。"], ["数数", "用循环、递归或概率模型估计操作次数。"], ["比较", "把不同方案放进同一个增长尺度，再判断取舍。"]], code: "function linearSearch(A, key) {\n  for (let i = 0; i < A.length; i++)\n    if (A[i] === key) return i;\n  return -1;\n}", cue: "数一数最坏情况下比较发生了几次；再问：有序数组会给你什么新选择？", anchor: "复杂度是沟通算法行为的语言，不是性能测试的替代品。", try: "为二分查找写出循环不变量。" },
  { id: 2, title: "分治", slug: "Split the structure, not just the input", tags: ["递归", "合并", "递推式"], summary: "分治的力量不在于把问题切小，而在于切开后能独立解决，并以低成本把答案重新接起来。", principles: [["01", "子问题要同类", "每一层仍在解决原问题的缩小版本，递归才有稳定的形状。"], ["02", "合并决定上限", "切分往往很便宜，真正的复杂度常藏在 combine 阶段。"], ["03", "递推要有边界", "T(n) 之外，还要写明基例和 n 不能整除时的处理。"]], steps: [["分", "用一个结构性规则把输入拆成互不干扰的部分。"], ["治", "递归地解决较小问题，直到基例可以直接回答。"], ["合", "利用有序性、区间或边界条件，把局部答案连成全局答案。"]], code: "function mergeSort(A) {\n  if (A.length <= 1) return A;\n  const mid = Math.floor(A.length / 2);\n  return merge(mergeSort(A.slice(0, mid)), mergeSort(A.slice(mid)));\n}", cue: "为 merge 单独计算一次成本；它解释了为什么不是 O(n log n) 之外的别的东西。", anchor: "递归树不是装饰，它把每层工作量和层数拆开给你看。", try: "把 mergesort 改成原地版本，再比较实现复杂度。" },
  { id: 3, title: "排序与选择", slug: "Order is a reusable data structure", tags: ["排序", "选择", "partition"], summary: "排序把一次性的杂乱输入转成可重复利用的秩序。选择问题则提醒我们：只要第 k 小，不一定要得到完整顺序。", principles: [["01", "比较模型有边界", "仅靠比较时，排序需要足够多的信息来区分所有排列。"], ["02", "partition 很有用", "围绕枢轴分区后，枢轴的最终位置立刻变成一个确定事实。"], ["03", "稳定性有语义", "相等键的相对次序是否保留，会影响多关键字排序与用户可见结果。"]], steps: [["选枢轴", "决定一个元素或随机样本，作为一次分区的参照。"], ["分区", "维护左右区域的不变量，把小于和大于枢轴的元素送往不同侧。"], ["缩小", "排序继续处理两边；选择只需进入包含第 k 个元素的一边。"]], code: "function partition(A, lo, hi) {\n  const pivot = A[hi];\n  let i = lo;\n  for (let j = lo; j < hi; j++)\n    if (A[j] <= pivot) [A[i++], A[j]] = [A[j], A[i]];\n  [A[i], A[hi]] = [A[hi], A[i]];\n  return i;\n}", cue: "写下循环结束时 i 的含义；它正是枢轴最终位置的证据。", anchor: "排序不是终点；它常是二分、扫描线和去重等算法的前处理。", try: "把 pivot 改成随机选择，记录最坏情况是否还常出现。" },
  { id: 4, title: "哈希与期望时间", slug: "Fast lookup by controlled collisions", tags: ["哈希表", "随机化", "装载因子"], summary: "哈希表不承诺没有碰撞，而是用合适的散列与装载策略，让碰撞在期望意义上保持可控。", principles: [["01", "键与槽分离", "哈希函数把键映到槽；相同槽不等于相同键，仍需做相等性检查。"], ["02", "装载因子是温度计", "元素数与槽数的比例持续上升时，链变长、探测变远，重散列就该登场。"], ["03", "期望需说明假设", "平均 O(1) 来自分布假设或随机化，不是对任何输入的无条件保证。"]], steps: [["散列", "把键压缩为数组位置，尽量均匀地使用槽位。"], ["解决碰撞", "用链地址法保存同槽键，或沿探测序列寻找空位。"], ["维护", "当负载超过阈值，扩大表并把元素重新放置。"]], code: "function put(table, key, value) {\n  const i = hash(key) % table.length;\n  for (const pair of table[i])\n    if (pair.key === key) return pair.value = value;\n  table[i].push({ key, value });\n}", cue: "让所有键都落进同一个槽，观察“平均 O(1)”在什么条件下会退化。", anchor: "快来自均匀分布与维护策略共同成立，而非 hash() 这个名字。", try: "为字符串键写一个很差和一个较好的哈希函数。" },
  { id: 5, title: "树与平衡", slug: "Keep the path short", tags: ["二叉搜索树", "旋转", "平衡"], summary: "搜索树把“有序”变成一条决策路径。若树退化为链，搜索优势消失；平衡策略的目标就是让高度始终可控。", principles: [["01", "搜索树有不变量", "每个节点左侧键更小、右侧键更大；递归结构让查询沿单一路径走。"], ["02", "高度决定代价", "查找、插入、删除只走根到叶的一条路径，关键不是节点数而是高度。"], ["03", "旋转保持顺序", "局部改造父子关系，却不改变中序遍历；它是平衡树的基本动作。"]], steps: [["落点", "按键比较向左或右下降，直到找到目标或空孩子。"], ["修改", "插入叶子、替换后继或删除节点，可能破坏局部平衡。"], ["修复", "依据高度、颜色或优先级做旋转，让坏情况不再累积。"]], code: "function find(node, key) {\n  while (node && node.key !== key)\n    node = key < node.key ? node.left : node.right;\n  return node;\n}", cue: "依次插入递增键，普通 BST 会变成什么形状？", anchor: "平衡树不是让每层完全一样，而是禁止高度持续偏向一边。", try: "画出一次左旋前后，哪些中序关系绝不能改变。" },
  { id: 6, title: "堆与优先队列", slug: "Always know the next candidate", tags: ["heap", "优先队列", "heapify"], summary: "堆不提供完整排序，却能用很少的结构约束，让你持续拿到当前最重要的元素。", principles: [["01", "局部顺序足够", "父节点不大于子节点，并不意味着兄弟之间有序；正是这点节省了维护成本。"], ["02", "数组天然适配", "完全二叉树按层存入数组，父子下标可以用简单算术得到。"], ["03", "修复沿一条路", "插入时上浮、删除顶时下沉；两者都只触及树高长度的路径。"]], steps: [["建堆", "从最后一个非叶节点开始向下修复，把无序数组收拢成堆。"], ["取顶", "移走根，把最后元素填上来，再向下恢复堆序。"], ["更新", "键变小或变大时，选择上浮或下沉，避免全局重排。"]], code: "function siftDown(A, i, n) {\n  while (2 * i + 1 < n) {\n    let c = 2 * i + 1;\n    if (c + 1 < n && A[c + 1] < A[c]) c++;\n    if (A[i] <= A[c]) break;\n    [A[i], A[c]] = [A[c], A[i]];\n    i = c;\n  }\n}", cue: "证明循环开始时 i 之下为什么一直是堆；它就是下沉操作的安全网。", anchor: "优先队列保存的不是“全部顺序”，而是下一步最值得处理的候选。", try: "用堆实现一个持续维护中位数的双堆结构。" },
  { id: 7, title: "图的遍历", slug: "Discovery order is information", tags: ["BFS", "DFS", "图", "连通性"], summary: "遍历并不只是“访问每个点”。BFS 给出按边数增长的层，DFS 则留下进入和离开的时间线；两种秩序能推出不同结论。", principles: [["01", "状态防止重复", "颜色、visited 集合或时间戳，保证每个顶点按可推理的方式被处理。"], ["02", "队列与栈塑造秩序", "BFS 的队列产生层次；DFS 的递归栈深入一条路径，再回溯。"], ["03", "边类型有含义", "树边、回边等分类能揭示环、祖先关系与有向图的结构。"]], steps: [["初始化", "选起点，赋予它初始状态和距离或时间。"], ["扩展", "从容器中取出一个已发现节点，扫描它的邻居。"], ["记录", "首次发现时设置前驱；这个前驱森林就是之后恢复路径的证据。"]], code: "function bfs(G, s) {\n  const dist = new Map([[s, 0]]), q = [s];\n  for (let head = 0; head < q.length; head++)\n    for (const v of G.get(q[head]))\n      if (!dist.has(v)) { dist.set(v, dist.get(q[head]) + 1); q.push(v); }\n  return dist;\n}", cue: "为什么节点第一次出队时的距离一定最短？用队列的入队顺序解释。", anchor: "遍历生成的树是算法输出的一部分，不只是实现里的临时变量。", try: "给 BFS 加 predecessor 映射，输出一条从 s 到任意点的路径。" },
  { id: 8, title: "最短路径", slug: "Relaxation improves a claim", tags: ["relax", "Dijkstra", "Bellman-Ford"], summary: "最短路径算法反复维护一个声明：当前距离上界还可以被哪条边改进。不同算法的差异，在于它们如何安排这些松弛操作。", principles: [["01", "距离是上界", "初始化为无穷大不是说不可达，而是承认还没有更好的证据。"], ["02", "松弛是局部推理", "若经过 u 到 v 更短，就更新 v 的上界和前驱；这是整个家族的共同动作。"], ["03", "负边改变策略", "贪心地确定一个点的最短距离，需要非负边；否则后续可能反悔。"]], steps: [["初始化", "源点为 0，其他点为 ∞，前驱为空。"], ["松弛", "考察边 (u,v)，判断 d[u] + w(u,v) 是否推翻 d[v]。"], ["终止", "当没有上界还能改进，或完成规定轮次，结果才可被接受。"]], code: "function relax(u, v, w, d, parent) {\n  if (d.get(u) + w < d.get(v)) {\n    d.set(v, d.get(u) + w);\n    parent.set(v, u);\n    return true;\n  }\n  return false;\n}", cue: "为 Bellman-Ford 画一个含负环的例子：为什么第 |V| 轮仍能改进是报警信号？", anchor: "算法不是在“找一条路”，而是在逐步收紧每个节点的最优性声明。", try: "把 Dijkstra 的线性选点替换成最小堆。" },
  { id: 9, title: "最小生成树", slug: "Connect everything without redundant cost", tags: ["MST", "Kruskal", "Prim", "cut"], summary: "最小生成树不是最短路径树。它追求的是以最小总权重连通所有顶点，而安全边的判断来自切分图的结构。", principles: [["01", "树意味着恰好连通", "n 个顶点的生成树有 n-1 条边；加入环里的重边通常没有必要。"], ["02", "切性质给安全边", "跨越任意尊重当前森林的切的最轻边，可以安全加入某棵 MST。"], ["03", "并查集管组件", "Kruskal 需要快速判断两端是否已连通；集合合并是它的节奏器。"]], steps: [["排序", "按权重从小到大查看候选边。"], ["判断", "如果边连接的是两个不同组件，它不会制造环。"], ["合并", "接受安全边并合并组件，直到只剩一个连通分量。"]], code: "for (const [u, v, w] of edges.sort(byWeight)) {\n  if (find(u) !== find(v)) {\n    tree.push([u, v, w]);\n    union(u, v);\n  }\n}", cue: "请不要用“它看起来最轻”证明正确；试着画出一条切，说明为什么它安全。", anchor: "贪心选择之所以可靠，需要一个结构定理替你兜底。", try: "实现带路径压缩和按秩合并的并查集。" },
  { id: 10, title: "动态规划", slug: "Remember overlapping answers", tags: ["DP", "子问题", "状态转移"], summary: "动态规划把指数级重复计算，改造成一张有方向的依赖表。难点从来不是填表，而是设计一个足以复用、又不过度膨胀的状态。", principles: [["01", "状态描述边界", "状态必须包含未来决策所需的全部信息，也不能把无关历史一起背上。"], ["02", "最优子结构要证明", "全局最优解里的局部选择，必须能替换为对应子问题的最优解。"], ["03", "顺序服从依赖", "自底向上填表需要保证用到的子状态已经就绪。"]], steps: [["定义", "用下标、容量、集合或区间说明一个子问题究竟在问什么。"], ["转移", "列出最后一步或第一次选择，写出状态之间的等式。"], ["恢复", "若需要实际方案，额外记录做出选择的指针，不只保留最优值。"]], code: "for (let i = 1; i <= m; i++)\n  for (let j = 1; j <= n; j++)\n    dp[i][j] = X[i - 1] === Y[j - 1]\n      ? dp[i - 1][j - 1] + 1\n      : Math.max(dp[i - 1][j], dp[i][j - 1]);", cue: "这是 LCS 的长度表。把箭头也存下来，才能从表格反向恢复一个公共子序列。", anchor: "DP 的核心不是记忆化本身，而是把问题组织成可复用的有向无环依赖。", try: "给 0/1 背包写出一维滚动数组版本，并解释为何容量要倒序。" },
  { id: 11, title: "贪心策略", slug: "Commit only when the structure permits it", tags: ["greedy", "exchange", "matroid"], summary: "贪心每一步都想立刻做一个看似最好的选择。它在某些问题上优雅得惊人，但前提是存在能证明“局部承诺不会堵死全局最优”的结构。", principles: [["01", "选择规则要具体", "“选最优的”太模糊；应明确是最早结束、最小权重，还是最大收益密度。"], ["02", "交换论证很常用", "把最优解中的一个选择替换成贪心选择，且不使答案变差。"], ["03", "失败例更重要", "当贪心不适用时，一个小反例往往比背规则更能校准直觉。"]], steps: [["排序", "按贪心准则组织候选，例如按结束时间。"], ["承诺", "接受当前可行且最符合准则的选择。"], ["维持可行", "更新边界或资源，让下一次判断只面对仍可能被接受的候选。"]], code: "let end = -Infinity, chosen = [];\nfor (const job of jobs.sort((a, b) => a.finish - b.finish))\n  if (job.start >= end) {\n    chosen.push(job);\n    end = job.finish;\n  }", cue: "活动选择为什么选最早结束，而不是最早开始或持续时间最短？各写一个反例。", anchor: "贪心的自信来自证明，不来自“每一步都显得合理”。", try: "用交换论证写出活动选择的正确性草稿。" },
  { id: 12, title: "摊还分析", slug: "A rare expensive step can still be cheap", tags: ["摊还", "势能", "动态表"], summary: "单次操作可能很贵，但一长串操作的平均代价可以很低。摊还分析不依赖随机输入；它为昂贵操作提前存下一点“信用”。", principles: [["01", "看序列，不看孤点", "目标是给任意操作序列一个总成本上界，而非假设某次操作幸运。"], ["02", "三种同一件事", "聚合法、记账法和势能法只是用不同语言解释预付成本。"], ["03", "势能必须非负", "初末势能差会进入总账；恰当的势函数要确保不会凭空借债。"]], steps: [["找尖峰", "识别偶发但昂贵的动作，例如动态数组扩容时的复制。"], ["分摊", "把一次大成本均摊到此前或此后的多次轻操作。"], ["求和", "证明任意前缀操作的总账都没有超支。"]], code: "function push(A, x) {\n  if (A.size === A.capacity) resize(A, 2 * A.capacity);\n  A.data[A.size++] = x;\n}", cue: "把 capacity 从 1 开始列出来：哪些 push 很贵？为什么前面已经有足够多的便宜 push 为它买单？", anchor: "摊还 O(1) 允许偶尔 O(n)，但要求任意长序列的总账都受控。", try: "用势能 Φ = 2·size − capacity 分析动态表扩容。" },
  { id: 13, title: "NP 完全性", slug: "Classify difficulty by reductions", tags: ["P", "NP", "归约", "复杂性"], summary: "面对一个看似无从下手的问题，复杂性理论首先问的不是“写什么代码”，而是“它与已知难题之间有什么可转换的关系”。", principles: [["01", "验证与求解不同", "一个候选解能否快速检查，和能否快速找到，是两件尚未证明等价的事。"], ["02", "归约传递难度", "若能把已知难题多项式时间转成新问题，新问题至少不比前者容易。"], ["03", "分类指导策略", "识别 NP 完全性后，近似、参数化、启发式或限制实例常比蛮力更诚实。"]], steps: [["选已知难题", "从一个已被证明困难的问题出发，而不是从目标问题倒推。"], ["构造转换", "把旧实例变成新实例，并证明 yes/no 答案严格对应。"], ["核对复杂度", "转换本身必须足够快；否则无法传递计算难度。"]], code: "function reduce(instance) {\n  // encode a known hard instance\n  // as an instance of the target problem\n  return targetInstance;\n}", cue: "归约箭头的方向最容易画反：你是用已知难题去说明新问题难，而不是相反。", anchor: "困难性证明不是失败声明，而是为算法选择划出一张更真实的地图。", try: "选一个熟悉的约束问题，试着写出它的验证器。" },
];

const KEYS = { theme: "algorithms-guide-theme", read: "algorithms-guide-read", current: "algorithms-guide-current" };
const storedRead = safeJson(localStorage.getItem(KEYS.read));
const state = { current: Number(localStorage.getItem(KEYS.current)) || 1, read: new Set(Array.isArray(storedRead) ? storedRead : []), query: "", filter: "all" };
if (!ROUTES.some((route) => route.id === state.current)) state.current = 1;
const els = { nav: document.querySelector("#routeNav"), reader: document.querySelector("#reader"), search: document.querySelector("#searchInput"), visible: document.querySelector("#visibleCount"), progressCount: document.querySelector("#progressCount"), progressText: document.querySelector("#progressText"), theme: document.querySelector("#themeToggle") };

function boot() { applyTheme(); bind(); render(); }
function bind() {
  els.search.addEventListener("input", (event) => { state.query = event.target.value.trim().toLowerCase(); renderNav(); });
  document.querySelector(".filter-row").addEventListener("click", (event) => { const button = event.target.closest("[data-filter]"); if (!button) return; state.filter = button.dataset.filter; document.querySelectorAll("[data-filter]").forEach((item) => item.setAttribute("aria-pressed", String(item === button))); renderNav(); });
  els.nav.addEventListener("click", (event) => { const button = event.target.closest("[data-route]"); if (button) selectRoute(Number(button.dataset.route), true); });
  els.reader.addEventListener("click", async (event) => { const done = event.target.closest("[data-done]"); if (done) toggleRead(state.current); const copy = event.target.closest("[data-copy]"); if (copy) await copyCode(copy); const nav = event.target.closest("[data-nav]"); if (nav) selectRoute(Number(nav.dataset.nav), true); });
  els.theme.addEventListener("click", () => { const next = document.documentElement.dataset.theme === "dark" ? "light" : "dark"; document.documentElement.dataset.theme = next; localStorage.setItem(KEYS.theme, next); els.theme.innerHTML = icon(next === "dark" ? "sun" : "moon"); refreshIcons(); });
  document.addEventListener("keydown", (event) => { if (event.metaKey || event.ctrlKey || event.altKey || event.target.matches("input,textarea,select")) return; if (event.key === "[") move(-1); if (event.key === "]") move(1); });
}
function render() { renderProgress(); renderNav(); renderReader(); refreshIcons(); }
function renderProgress() { els.progressCount.textContent = state.read.size; els.progressText.textContent = `${state.read.size} / ${ROUTES.length}`; }
function renderNav() { const routes = filtered(); els.visible.textContent = routes.length; els.nav.innerHTML = routes.map((route) => { const read = state.read.has(route.id); return `<button class="route-button" type="button" data-route="${route.id}" aria-current="${route.id === state.current}"><span class="route-no">${String(route.id).padStart(2,"0")}</span><span class="route-title">${escapeHtml(route.title)}</span><span class="route-state ${read ? "is-read" : ""}" aria-label="${read ? "已读" : "未读"}">${read ? icon("check") : ""}</span></button>`; }).join(""); refreshIcons(); }
function renderReader() { const route = currentRoute(); const read = state.read.has(route.id); const prev = ROUTES[route.id - 2], next = ROUTES[route.id]; els.reader.innerHTML = `<section class="reader-intro"><p class="route-index">ROUTE ${String(route.id).padStart(2,"0")}</p><div class="reader-title-row"><div><h2 class="reader-title">${escapeHtml(route.title)}</h2><p class="route-slug">${escapeHtml(route.slug)}</p></div><button class="done-button ${read ? "is-read" : ""}" type="button" data-done aria-pressed="${read}">${icon(read ? "check-circle-2" : "circle")}<span>${read ? "已读完" : "标为读完"}</span></button></div><p class="reader-summary">${escapeHtml(route.summary)}</p><div class="tag-row">${route.tags.map((tag) => `<span class="tag"># ${escapeHtml(tag)}</span>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>01</span> 三个抓手</h2><div class="principle-grid">${route.principles.map(([no,title,body]) => `<article class="principle-card"><span>${no}</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></article>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>02</span> 证明与实现的路径</h2><div class="proof-path">${route.steps.map(([title,body], index) => `<div class="proof-step"><span>${index + 1}</span><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></div></div>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>03</span> 代码切片</h2><div class="code-card"><div class="code-top"><span>algorithm-note.js</span><button class="copy-button" type="button" data-copy>${icon("copy")}<b>复制代码</b></button></div><pre><code>${escapeHtml(route.code)}</code></pre><p class="code-caption"><b>CHECK</b>　${escapeHtml(route.cue)}</p></div></section><section class="reader-section"><h2 class="section-title"><span>04</span> 留下一点摩擦</h2><div class="takeaway"><div>${escapeHtml(route.anchor)}</div><div><span>TRY NEXT</span><strong>${escapeHtml(route.try)}</strong></div></div></section><nav class="reader-nav" aria-label="前后主题">${navButton(prev,"← 上一条")}${navButton(next,"下一条 →",true)}</nav>`; document.title = `${route.title} · 算法导读`; refreshIcons(); }
function navButton(route, label, end = false) { return route ? `<button type="button" data-nav="${route.id}" ${end ? "" : ""}><span>${label}</span><b>${escapeHtml(route.title)}</b></button>` : `<button type="button" disabled></button>`; }
function filtered() { return ROUTES.filter((route) => { const read = state.read.has(route.id); const matchFilter = state.filter === "all" || (state.filter === "read" ? read : !read); const text = [route.title, route.slug, route.summary, ...route.tags, ...route.principles.flat()].join(" ").toLowerCase(); return matchFilter && (!state.query || text.includes(state.query)); }); }
function currentRoute() { return ROUTES.find((route) => route.id === state.current) || ROUTES[0]; }
function selectRoute(id, scrollMobile) { if (!ROUTES.some((route) => route.id === id)) return; state.current = id; localStorage.setItem(KEYS.current, String(id)); renderNav(); renderReader(); if (scrollMobile && window.innerWidth <= 680) els.reader.scrollIntoView({ behavior: "smooth", block: "start" }); }
function move(delta) { selectRoute(Math.max(1, Math.min(ROUTES.length, state.current + delta)), true); }
function toggleRead(id) { state.read.has(id) ? state.read.delete(id) : state.read.add(id); localStorage.setItem(KEYS.read, JSON.stringify([...state.read])); renderProgress(); renderNav(); renderReader(); }
async function copyCode(button) { const old = button.querySelector("b").textContent; const text = currentRoute().code; try { await navigator.clipboard.writeText(text); } catch { const area = document.createElement("textarea"); area.value = text; area.style.cssText = "position:fixed;opacity:0"; document.body.append(area); area.select(); document.execCommand("copy"); area.remove(); } button.querySelector("b").textContent = "已复制"; setTimeout(() => { if (button.isConnected) button.querySelector("b").textContent = old; }, 1400); }
function applyTheme() { const stored = localStorage.getItem(KEYS.theme); const theme = stored || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"); document.documentElement.dataset.theme = theme; els.theme.innerHTML = icon(theme === "dark" ? "sun" : "moon"); }
function safeJson(value) { try { return JSON.parse(value || "null"); } catch { return null; } }
function icon(name) { return `<i data-lucide="${name}"></i>`; }
function escapeHtml(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function refreshIcons() { if (window.lucide) window.lucide.createIcons(); }
boot();
