const MODULES = [
  { id: 1, title: "语言建模与概率", slug: "Predicting the next unit of language", tags: ["language model", "cross-entropy", "perplexity"], summary: "语言模型把序列理解为条件概率的连乘：在给定上下文时，为下一个 token 分配一份概率质量。真正要追问的是，训练目标是否让模型把概率放在了正确的地方。", lenses: [["01", "任务不是复读", "模型学习的是条件分布 p(x_t | x_<t)，不是把训练句子背进参数。"], ["02", "损失是负对数", "把正确 token 的概率推高，等价于最小化它的负对数概率；低概率的正确答案会得到更大惩罚。"], ["03", "困惑度要会读", "perplexity 是平均每步不确定性的指数化版本，只能在相同 tokenization 下比较。"]], viz: "probability", visualLabel: "conditional probability flow", visualNote: "每一个箭头都是一次“给定前文、预测下一个 token”的条件分布。", formula: ["L = −Σₜ log p(xₜ | x₍₍ₜ₎₎)", "把整句的联合概率拆成自回归条件概率；训练时通常用 teacher forcing 一次并行计算所有位置。", [["log", "把连乘变为可加的稳定目标"], ["Σ", "每个位置都提供一个监督信号"], ["min", "等价于让正确 token 概率更高"]]], trace: [["准备移位样本", "输入是 x₁…xₜ₋₁，标签是 x₂…xₜ；这个一个位置的错位定义了 next-token prediction。"], ["产生 logits", "模型为词表中每个候选给出未归一化得分，而不是立即输出一个词。"], ["归一化与回传", "softmax 将 logits 变为分布，交叉熵把错误分配转换成可微的梯度。"]], code: "logits = model(input_ids)[:, :-1]\ntargets = input_ids[:, 1:]\nloss = F.cross_entropy(\n    logits.reshape(-1, logits.size(-1)),\n    targets.reshape(-1)\n)", check: "检查 padding token 是否被 mask；否则模型会认真学习“预测补齐符”的无意义规律。", failure: ["指标幻觉", "同样的 perplexity 并不保证同样的事实性、帮助性或安全性；它只衡量 token 级的拟合。"], experiment: ["做一个探针", "固定模型，分别在常见句和罕见专名句上观察 top-k 概率分布。"] },
  { id: 2, title: "词向量与语义几何", slug: "Meaning as a position in a learned space", tags: ["embedding", "word2vec", "similarity"], summary: "词向量不为词写词典式定义，而是让词在与上下文的共现预测中获得位置。距离、方向与聚类因此成为可以检查、也容易误读的语义线索。", lenses: [["01", "分布塑造表示", "经常出现在相似上下文中的词，会被训练目标拉向相近的表示区域。"], ["02", "相似性不是同义", "cosine 相近可能来自主题、搭配或语法角色；向量邻居需要结合语料解释。"], ["03", "负采样在做对比", "每个正共现对都与若干噪声词对比，让模型把有限容量用在可区分的关系上。"]], viz: "embedding", visualLabel: "embedding neighbourhood", visualNote: "二维图只是高维向量空间的投影：看趋势，不要把投影中的距离当作完整真相。", formula: ["sim(u, v) = u · v / (‖u‖‖v‖)", "余弦相似度忽略向量长度，关注方向夹角；它常用于检索，却不是唯一可用的度量。", [["u · v", "方向一致时点积更大"], ["‖u‖‖v‖", "归一化掉长度差异"], ["cos", "值越接近 1，方向越一致"]]], trace: [["定义正样本", "从滑动窗口中取中心词与上下文词；窗口大小本身就是建模假设。"], ["抽取负样本", "按某个噪声分布采样未共现词，形成对比项。"], ["更新两个表", "输入向量与输出向量都被更新；最终使用哪一个或如何合并，需要明确说明。"]], code: "score_pos = (center * context).sum(-1)\nscore_neg = center @ negatives.T\nloss = -F.logsigmoid(score_pos).mean() \\\n       - F.logsigmoid(-score_neg).mean()", check: "不要把向量算术当作规律证明；先检查它是否被词频、职业刻板印象或数据缺口劫持。", failure: ["几何偏见", "训练语料里的社会偏见会进入邻域与方向；“只是统计”并不等于没有影响。"], experiment: ["做一个对照", "比较 raw cosine 与 L2-normalized embedding 的近邻，记录变化最大的词。"] },
  { id: 3, title: "神经网络与训练信号", slug: "Every representation is shaped by a gradient", tags: ["backprop", "activation", "optimization"], summary: "神经 NLP 的每层表示都不是孤立的特征工程，而是损失函数经由链式法则反向塑形的结果。读模型时，应追踪哪里产生误差信号、哪里可能让它消失。", lenses: [["01", "前向定义计算图", "线性层、非线性、归一化和残差连接共同决定信息如何变形。"], ["02", "反向分配责任", "梯度告诉每个参数：微小改变会让当前损失往哪个方向变化。"], ["03", "优化不是自动成功", "学习率、批量噪声、初始化和尺度都会影响同一目标能否真的被优化。"]], viz: "gradient", visualLabel: "forward values / backward gradients", visualNote: "实线向右传递激活值，虚线向左传递梯度；两条路径都值得被检查。", formula: ["∂L/∂W = (∂L/∂h) · (∂h/∂W)", "链式法则让局部导数沿计算图相乘。层数越深，尺度控制越重要。", [["L", "最终监督目标"], ["h", "中间表示或隐藏状态"], ["W", "需要更新的参数矩阵"]]], trace: [["记录激活", "前向过程需要保留足以计算局部导数的信息。"], ["传播局部梯度", "从损失开始，逐节点计算对输入和参数的偏导。"], ["更新并验证", "先看梯度范数、loss 曲线和一个极小数据集能否过拟合，再谈大规模训练。"]], code: "optimizer.zero_grad()\nlogits = model(batch.tokens)\nloss = F.cross_entropy(logits, batch.labels)\nloss.backward()\ntorch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\noptimizer.step()", check: "若 loss 不降，先试图在 8 个样本上过拟合；这比盲调架构更快定位数据或实现错误。", failure: ["静默退化", "梯度爆炸、全零 mask 或错误的 label shift 可能不报错，却让训练看似正常地失败。"], experiment: ["记一条曲线", "同时记录 loss、梯度范数和参数范数；观察它们何时开始脱钩。"] },
  { id: 4, title: "Tokenization 与词表", slug: "The first modeling decision happens before the model", tags: ["BPE", "subword", "tokenization"], summary: "tokenizer 决定模型看见的基本单位，也影响序列长度、词表覆盖、压缩率与跨语言公平性。它不是预处理细节，而是模型接口的一部分。", lenses: [["01", "开放词表需要分解", "子词把未登录词拆成可组合片段，避免词表无限膨胀。"], ["02", "边界会改变难度", "同一句话切成不同 token，模型面对的预测步数与条件结构都会变化。"], ["03", "压缩不等于公平", "高资源语言的高频片段更容易被合并；少数语言可能得到更长、更碎的序列。"]], viz: "token", visualLabel: "subword segmentation", visualNote: "tokenizer 先切开语言，再交给模型。切法不同，后续的一切统计都会不同。", formula: ["tokens = BPE(text; merges, vocab)", "BPE 反复合并高频相邻片段；merges 是由训练语料学到的压缩历史。", [["text", "原始字符序列"], ["merges", "预先学习的合并规则"], ["vocab", "模型实际可读取的 ID 集合"]]], trace: [["规范化", "明确是否保留大小写、空格、emoji、Unicode 变体；这些决定必须可复现。"], ["切分", "用训练好的规则把字符串变为子词，再映射到整数 ID。"], ["审计", "比较不同语言、专名和代码片段的 token 长度，找出不成比例的成本。"]], code: "pieces = tokenizer.tokenize(\"unhappiness\")\nids = tokenizer.convert_tokens_to_ids(pieces)\nprint(list(zip(pieces, ids)))", check: "训练与推理必须使用同一套 tokenizer、同一版本词表和同一特殊 token 约定。", failure: ["长度偏置", "某类文本被切得更长，会更快耗尽 context budget，也会产生更高的按 token 计费。"], experiment: ["做一个表", "选中文、英文、代码和罕见人名，各比较 token 数与字符数的比例。"] },
  { id: 5, title: "序列模型与 LSTM", slug: "Carry a state, decide what to forget", tags: ["RNN", "LSTM", "hidden state"], summary: "循环网络让每一步的状态依赖此前状态，第一次把“顺序”真正纳入神经模型。但长距离依赖会让梯度穿过太多时间步，LSTM 的门正是为此而设计。", lenses: [["01", "隐藏状态是压缩", "hₜ 必须把过去压进固定维度；它不可能完整保存所有细节。"], ["02", "门是信息路由", "遗忘、输入和输出门决定哪些内容保留、写入、暴露。"], ["03", "并行性是代价", "RNN 的时间依赖阻止同一序列内的完全并行，这是 Transformer 取代它的重要原因。"]], viz: "sequence", visualLabel: "recurrent state transition", visualNote: "每个时间步接收当前 token 与前一状态；长距离信息必须穿过这条重复路径。", formula: ["hₜ = tanh(Wₓxₜ + Wₕhₜ₋₁ + b)", "最基本的 RNN 状态转移。LSTM/GRU 用更复杂的可控通路替换单一 tanh。", [["xₜ", "当前输入表示"], ["hₜ₋₁", "此前压缩的上下文"], ["hₜ", "传给下一步的新状态"]]], trace: [["嵌入输入", "把 token ID 映射到稠密向量，作为每个时间步的 xₜ。"], ["滚动状态", "从左到右更新 h；训练时通过时间反向传播把误差送回过去。"], ["处理边界", "padding、句子结束和 batch 内不同长度，都需要明确的 mask 或 packing 策略。"]], code: "h = torch.zeros(batch, hidden)\nfor x_t in embeddings.unbind(dim=1):\n    h = torch.tanh(x_t @ Wx + h @ Wh + b)\n    states.append(h)", check: "把一个依赖放到句首和句尾分别训练；性能差异能直观看出模型的有效记忆长度。", failure: ["遗忘过快", "即使 LSTM 缓解了梯度问题，也不能保证模型愿意保留任务真正需要的远处信息。"], experiment: ["造一个任务", "生成“开头给类别、末尾再问类别”的合成序列，比较 RNN 与 LSTM。"] },
  { id: 6, title: "Seq2Seq 与束搜索", slug: "Generate a sequence without seeing the answer", tags: ["encoder-decoder", "beam search", "MT"], summary: "序列到序列模型把输入压成条件上下文，再一步步生成目标。训练中有标准答案可喂给解码器，推理中却只能依赖自己刚生成的 token——这就是 exposure bias 的起点。", lenses: [["01", "编码与解码分工", "encoder 建立输入表示，decoder 在这个条件下定义目标序列的概率。"], ["02", "搜索不是训练", "模型学的是局部条件概率；beam search 是在推理时近似寻找高概率整句的算法。"], ["03", "长度需要校正", "概率连乘偏好短句，实际解码通常加入长度惩罚或归一化。"]], viz: "beam", visualLabel: "beam search tree", visualNote: "束搜索保存多个候选前缀；宽度变大不总是更好，因为模型概率与人类偏好并非同一目标。", formula: ["score(y) = Σₜ log p(yₜ | y_<t, x) / len(y)^α", "用对数累加候选概率，再用长度项避免过度偏好极短序列。", [["beam", "每步保留的候选数"], ["α", "长度惩罚强度"], ["EOS", "候选结束的明确边界"]]], trace: [["编码输入", "得到 source 的表示或初始 decoder 状态。"], ["扩展候选", "对当前每条前缀计算下一个 token 的 top-k，形成更多暂时候选。"], ["裁剪与完成", "按归一化分数保留 beam 条路径，直到足够候选生成 EOS 或达到长度限制。"]], code: "beams = [([bos_id], 0.0)]\nfor _ in range(max_len):\n    expanded = extend_all(beams, model)\n    beams = topk(expanded, k=beam_size, key=length_norm)\n    if all_finished(beams): break", check: "beam size 从 1 增大到 8 时，自动指标和人工偏好可能反向变化；别只看前者。", failure: ["暴露偏差", "训练看到真实前缀、推理看到自己的错误前缀，误差会在生成过程中累积。"], experiment: ["看候选集", "打印每一步的 beam，找出哪一个早期 token 改变了最终翻译走向。"] },
  { id: 7, title: "注意力：可微的检索", slug: "Let each token choose its context", tags: ["attention", "query-key-value", "alignment"], summary: "注意力让一个查询向量对所有候选位置打分，再以软权重汇聚它们的 value。它既是信息路由机制，也是把长距离依赖从“穿过很多步”改为“一次直接访问”。", lenses: [["01", "Q、K、V 分工", "query 表示当前需要什么，key 表示每个位置提供什么索引，value 是最终被读取的内容。"], ["02", "softmax 是软选择", "权重非负且和为 1；它允许模型在多个位置之间分配注意力。"], ["03", "权重不是解释终点", "attention map 很有启发，但不能自动证明因果贡献或模型的全部推理过程。"]], viz: "attention", visualLabel: "scaled dot-product attention", visualNote: "热图行表示 query、列表示 key；颜色只是一次路由的快照，而不是完整的因果解释。", formula: ["Attention(Q,K,V) = softmax(QKᵀ / √dₖ) V", "缩放项控制点积随维度增长的方差，让 softmax 不会过早饱和。", [["QKᵀ", "每个 query 对 key 的兼容度"], ["√dₖ", "稳定 score 的尺度"], ["V", "按权重读出的信息内容"]]], trace: [["投影三种角色", "同一输入表示经不同矩阵得到 Q、K、V，这给每个 head 独立的路由空间。"], ["计算权重", "点积、mask、缩放、softmax 依次决定哪些位置可看以及看多少。"], ["混合 value", "将权重乘到 V 上并求和，得到带上下文的新表示。"]], code: "scores = (Q @ K.transpose(-2, -1)) / math.sqrt(d_k)\nscores = scores.masked_fill(mask == 0, float('-inf'))\nweights = scores.softmax(dim=-1)\ncontext = weights @ V", check: "先断言 mask 后每行权重仍然近似为 1；这是发现 -inf、维度或广播错误的快办法。", failure: ["偷看未来", "自回归模型若没有 causal mask，就会在训练时读取目标答案后面的 token，得到虚假的低 loss。"], experiment: ["画一张图", "分别可视化有 mask 和无 mask 的 attention matrix，检查上三角是否真的被清零。"] },
  { id: 8, title: "Transformer：表示的层层重写", slug: "Context by parallel interaction", tags: ["transformer", "multi-head", "residual"], summary: "Transformer 用自注意力在同一层让所有 token 直接交流，再用逐位置前馈网络重新加工每个位置。多层堆叠后，表示从局部词形逐步变为任务相关的上下文特征。", lenses: [["01", "位置必须显式注入", "自注意力本身对排列不敏感；位置编码或位置偏置告诉模型谁在前谁在后。"], ["02", "多头是多种路由", "不同 head 可以学习不同关系模式，但不应把每个 head 强行赋予单一语言学标签。"], ["03", "残差保护信息", "残差和归一化让深层网络更易优化，也允许后层在必要时接近恒等映射。"]], viz: "transformer", visualLabel: "transformer encoder block", visualNote: "每个 block 都是一次“跨 token 混合 + 单 token 重写”；堆叠并非简单重复。", formula: ["Hˡ⁺¹ = LN(Hˡ + MHA(Hˡ)) → LN(· + FFN(·))", "注意力在 token 间交换信息，FFN 在每个位置的特征维度上进行非线性变换。", [["MHA", "多头注意力混合上下文"], ["FFN", "逐位置的特征重映射"], ["LN + residual", "稳定深层训练与信息流"]]], trace: [["嵌入加位置", "token embedding 与位置信息在进入第一层前组合。"], ["重复 block", "每层先路由上下文，再独立加工每个 token 的通道特征。"], ["读出任务", "最后表示可接语言模型头、分类头、检索头或其他任务接口。"]], code: "x = token_embed(ids) + position_embed(pos)\nfor block in blocks:\n    x = x + block.attn(block.norm1(x), mask)\n    x = x + block.ffn(block.norm2(x))\nlogits = lm_head(x)", check: "关注序列长度增长时显存的变化：标准 self-attention 的矩阵成本是 O(n²)。", failure: ["位置失配", "训练与推理的位置编码、最大长度或 RoPE 缩放策略不一致，会产生微妙但严重的退化。"], experiment: ["抓一层表示", "比较同一个词在不同句子里的最终 embedding，观察上下文如何改变它。"] },
  { id: 9, title: "预训练与上下文表示", slug: "Learn general structure before a narrow task", tags: ["BERT", "GPT", "pretraining"], summary: "预训练先在大规模无标注文本上学习语言规律，再用少量任务数据调整。关键不是“数据多”，而是预训练目标、数据分布和下游接口之间是否真的对齐。", lenses: [["01", "目标决定可用信息", "masked LM 可双向利用上下文；causal LM 只能看左侧，适合生成。"], ["02", "迁移依赖接口", "同一 backbone 在分类、抽取、检索和生成任务上需要不同读出方式。"], ["03", "规模隐藏分布问题", "更大语料也可能放大重复、泄漏、偏见或低质量文本的影响。"]], viz: "mask", visualLabel: "bidirectional vs causal context", visualNote: "同一序列在不同 mask 下可访问的信息完全不同；目标函数决定模型学习到的条件关系。", formula: ["Lₘₐₛₖ = −Σ_{i∈M} log p(xᵢ | x_\M)", "只对被遮住的位置计算预测损失；M 的采样策略会影响模型学到什么。", [["M", "被遮住的位置集合"], ["x_\M", "对这些位置不可见的上下文"], ["objective", "决定双向或单向条件化"]]], trace: [["构造 corruption", "选择 mask、replace 或保留哪些 token，形成训练输入与目标。"], ["预训练表示", "模型被迫从周围 token 恢复缺失信息，积累可迁移的上下文特征。"], ["连接下游", "选择 frozen feature、轻量 adapter 或全量 fine-tune，并验证是否过拟合小数据。"]], code: "mask = sample_mask(input_ids, rate=0.15)\nlabels = input_ids.masked_fill(~mask, -100)\ncorrupted = replace_masked_tokens(input_ids, mask)\nloss = model(corrupted, labels=labels).loss", check: "对比同一预训练模型 frozen 与 fine-tune 的结果；差距能说明下游数据量和任务距离。", failure: ["数据泄漏", "预训练语料包含测试答案或近重复样本，会让 benchmark 分数失去解释力。"], experiment: ["做一张消融表", "逐步减少可训练参数比例，记录指标、训练时间和稳定性。"] },
  { id: 10, title: "生成、采样与对齐", slug: "A decoding policy changes the model you experience", tags: ["sampling", "temperature", "top-p"], summary: "同一个语言模型在不同解码策略下会表现得像不同系统。温度、top-k、nucleus sampling 和重复惩罚不是“展示层参数”，而是在重新定义输出分布。", lenses: [["01", "温度重塑尖锐度", "T < 1 放大概率差异，T > 1 拉平分布；它不能凭空增加事实知识。"], ["02", "截断控制尾部", "top-k 与 top-p 排除低概率 token，减少偶发离题，也可能切掉必要的罕见词。"], ["03", "偏好不是似然", "人类喜欢的回答不必是训练文本中最可能的续写；对齐需要额外的偏好信号与评估。"]], viz: "decode", visualLabel: "temperature and nucleus sampling", visualNote: "柱形高度是 token 概率。不同解码策略会从同一 logits 中抽出不同的可行动作空间。", formula: ["pᵢ(T) = exp(zᵢ/T) / Σⱼ exp(zⱼ/T)", "temperature 在 softmax 前缩放 logits；注意 T→0 时分布趋向 argmax。", [["zᵢ", "模型原始 logit"], ["T", "随机性与尖锐度控制"], ["top-p", "最小累计概率候选集"]]], trace: [["得到 logits", "模型只输出下一 token 的得分，尚未决定选哪个。"], ["变换分布", "应用 temperature、惩罚、top-k/top-p 和 mask，得到采样分布。"], ["循环生成", "抽样 token 写回上下文，直到 EOS、长度上限或工具调用边界。"]], code: "logits = logits / temperature\nprobs = torch.softmax(logits, dim=-1)\nkeep = nucleus_mask(probs, p=0.9)\nnext_id = torch.multinomial(probs * keep, 1)", check: "记录随机种子与完整解码参数；否则一次“模型变好/变坏”的观察不可复现。", failure: ["确定性幻觉", "greedy decoding 看起来稳定，却可能反复选择局部高概率、全局质量很差的常见短语。"], experiment: ["做一个网格", "对同一 prompt 扫描 temperature × top-p，盲评事实性、重复和新颖性。"] },
  { id: 11, title: "评估：分数之外的证据", slug: "Measure the behavior you actually care about", tags: ["evaluation", "calibration", "human eval"], summary: "NLP 评估最危险的时刻，是一个单一分数让人停止提问。自动指标、人工偏好、分布切片、置信度和错误样本需要共同构成一条证据链。", lenses: [["01", "指标对应任务假设", "BLEU、F1、accuracy、ROUGE 各自奖励不同现象；先确认它与真实目标是否同向。"], ["02", "平均值藏住切片", "总体提升可能来自容易样本，而关键领域、低资源语言或长文本反而退化。"], ["03", "人评需要协议", "任务说明、抽样、盲评、标注一致性与不确定性范围，决定结果是否可信。"]], viz: "evaluation", visualLabel: "evaluation evidence stack", visualNote: "自动分数只是第一层。进一步需要分布切片、校准曲线、人工偏好和具体错误案例。", formula: ["ECE = Σₘ |Bₘ|/n · |acc(Bₘ) − conf(Bₘ)|", "校准误差比较预测置信度与实际准确率；高 accuracy 不保证模型知道自己何时会错。", [["Bₘ", "一组相近置信度的样本"], ["acc", "该组实际正确率"], ["conf", "该组平均预测置信度"]]], trace: [["写出主张", "先明确要证明什么：更准确、更鲁棒、更公平，还是更受偏好？"], ["组合证据", "用自动指标、切片结果和定性样本从不同角度检验主张。"], ["报告不确定性", "给出样本量、区间、失败案例与已知局限，避免把偶然波动叙述成结论。"]], code: "for bucket in confidence_bins(predictions):\n    acc = bucket.correct.mean()\n    conf = bucket.prob.mean()\n    ece += len(bucket) / n * abs(acc - conf)", check: "任何综合分数旁边都至少放 5 个随机抽取的错误样本；它们常比均值更快暴露系统性问题。", failure: ["benchmark 过拟合", "反复依据同一评测集改提示词或模型，会把测试集慢慢变成开发集。"], experiment: ["设计切片", "按长度、语言、实体类型或置信度分桶，比较每桶的指标与典型失败。"] },
  { id: 12, title: "调试、鲁棒性与责任", slug: "Treat failures as part of the specification", tags: ["robustness", "bias", "debugging"], summary: "一个 NLP 系统的边界不只在代码里，也在数据、提示、解码、部署上下文与用户行为中。成熟的实践不是假设它不会失败，而是为失败设计观测与退出机制。", lenses: [["01", "先做数据单元测试", "样本、标签、mask、token 长度和 train/test 切分都应有可自动检查的约束。"], ["02", "对抗不是恶意专属", "拼写扰动、格式变化、罕见实体和上下文注入，都是正常世界会给模型的压力。"], ["03", "能力与权限分开", "模型能生成某种内容，不代表系统就应执行相应动作；边界需要产品与工程共同实现。"]], viz: "diagnostic", visualLabel: "failure-to-fix loop", visualNote: "把错误收集、分类、复现、修复和回归测试连接成闭环，模型改动才不会反复制造旧问题。", formula: ["risk = likelihood × impact × exposure", "一个简单的风险分解：既看错误多不多，也看发生时的后果和它会触及多少用户。", [["likelihood", "发生频率或触发条件"], ["impact", "错误造成的实际伤害"], ["exposure", "受影响的范围与可见性"]]], trace: [["捕获失败", "记录输入类型、模型版本、解码参数和用户反馈，同时保护隐私。"], ["归因分类", "区分数据覆盖、训练目标、检索、提示、工具或界面诱导造成的问题。"], ["修复与回归", "将每个代表性失败变成可重复的测试，确保下一次改动不会悄悄带回它。"]], code: "assert train_ids.isdisjoint(test_ids)\nassert (attention_mask.sum(-1) > 0).all()\nassert labels[padding_positions].eq(ignore_index).all()\nlog_failure(example, model_version, decode_config)", check: "把一次真实失败写成最小可复现样本，并在修复后永久加入 regression suite。", failure: ["只修表面", "只靠一条提示词补丁压住个案，常会把问题推向未观察到的输入区域。"], experiment: ["做一次红队", "邀请同伴用拼写、方言、长上下文和冲突指令系统性挑战你的任务定义。"] }
];

const KEYS = { theme: "cs224n-nlp-theme", read: "cs224n-nlp-read", current: "cs224n-nlp-current" };
const VISUAL_ASSETS = {
  probability: "language-model",
  embedding: "embedding",
  gradient: "gradient",
  token: "tokenization",
  sequence: "rnn",
  beam: "beam",
  attention: "attention",
  transformer: "transformer",
  mask: "mask",
  decode: "decode",
  evaluation: "evaluation",
  diagnostic: "diagnostic",
};
const storedRead = safeJson(localStorage.getItem(KEYS.read));
const state = { current: Number(localStorage.getItem(KEYS.current)) || 1, read: new Set(Array.isArray(storedRead) ? storedRead : []), query: "", filter: "all" };
if (!MODULES.some((item) => item.id === state.current)) state.current = 1;
const els = { nav: document.querySelector("#moduleNav"), reader: document.querySelector("#reader"), search: document.querySelector("#searchInput"), visible: document.querySelector("#visibleCount"), progressCount: document.querySelector("#progressCount"), progressText: document.querySelector("#progressText"), theme: document.querySelector("#themeToggle") };

function boot() { applyTheme(); bind(); render(); }
function bind() {
  els.search.addEventListener("input", (event) => { state.query = event.target.value.trim().toLowerCase(); renderNav(); });
  document.querySelector(".filter-row").addEventListener("click", (event) => { const button = event.target.closest("[data-filter]"); if (!button) return; state.filter = button.dataset.filter; document.querySelectorAll("[data-filter]").forEach((item) => item.setAttribute("aria-pressed", String(item === button))); renderNav(); });
  els.nav.addEventListener("click", (event) => { const button = event.target.closest("[data-module]"); if (button) selectModule(Number(button.dataset.module), true); });
  els.reader.addEventListener("click", async (event) => { const done = event.target.closest("[data-done]"); if (done) { toggleRead(state.current); return; } const copy = event.target.closest("[data-copy]"); if (copy) await copyCode(copy); const nav = event.target.closest("[data-nav]"); if (nav) selectModule(Number(nav.dataset.nav), true); });
  els.theme.addEventListener("click", () => { const next = document.documentElement.dataset.theme === "dark" ? "light" : "dark"; document.documentElement.dataset.theme = next; localStorage.setItem(KEYS.theme, next); els.theme.innerHTML = icon(next === "dark" ? "sun" : "moon"); refreshIcons(); });
  document.addEventListener("keydown", (event) => { if (event.metaKey || event.ctrlKey || event.altKey || event.target.matches("input,textarea,select")) return; if (event.key === "[") move(-1); if (event.key === "]") move(1); });
}
function render() { renderProgress(); renderNav(); renderReader(); refreshIcons(); }
function renderProgress() { els.progressCount.textContent = state.read.size; els.progressText.textContent = `${state.read.size} / ${MODULES.length}`; }
function renderNav() { const modules = filteredModules(); els.visible.textContent = modules.length; els.nav.innerHTML = modules.map((item) => { const read = state.read.has(item.id); return `<button class="module-button" type="button" data-module="${item.id}" aria-current="${item.id === state.current}"><span class="module-no">${String(item.id).padStart(2,"0")}</span><span class="module-title">${escapeHtml(item.title)}</span><span class="module-state ${read ? "is-read" : ""}" aria-label="${read ? "已读" : "未读"}">${read ? icon("check") : ""}</span></button>`; }).join(""); refreshIcons(); }
function renderReader() { const item = currentModule(); const read = state.read.has(item.id); const prev = MODULES[item.id - 2], next = MODULES[item.id]; els.reader.innerHTML = `<section class="reader-intro"><p class="module-index">MODULE ${String(item.id).padStart(2,"0")}</p><div class="reader-title-row"><div><h2 class="reader-title">${escapeHtml(item.title)}</h2><p class="module-slug">${escapeHtml(item.slug)}</p></div><button class="done-button ${read ? "is-read" : ""}" type="button" data-done aria-pressed="${read}">${icon(read ? "check-circle-2" : "circle")}<span>${read ? "已读完" : "标为读完"}</span></button></div><p class="reader-summary">${escapeHtml(item.summary)}</p><div class="tag-row">${item.tags.map((tag) => `<span class="tag"># ${escapeHtml(tag)}</span>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>01</span> 模型的三个抓手</h2><div class="lens-grid">${item.lenses.map(([no,title,body]) => `<article class="lens-card"><span>${no}</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></article>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>02</span> 结构图：先看信息怎样流</h2>${renderVisual(item)}</section><section class="reader-section"><h2 class="section-title"><span>03</span> 公式：它在约束什么</h2>${renderFormula(item)}</section><section class="reader-section"><h2 class="section-title"><span>04</span> 训练或推理的执行路径</h2><div class="trace-list">${item.trace.map(([title,body], index) => `<div class="trace-step"><span>${index + 1}</span><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></div></div>`).join("")}</div></section><section class="reader-section"><h2 class="section-title"><span>05</span> 代码切片</h2><div class="code-card"><div class="code-top"><span>nlp-lab.py</span><button class="copy-button" type="button" data-copy>${icon("copy")}<b>复制代码</b></button></div><pre><code>${escapeHtml(item.code)}</code></pre><p class="code-caption"><b>CHECK</b>　${escapeHtml(item.check)}</p></div></section><section class="reader-section"><h2 class="section-title"><span>06</span> 失败模式与实验</h2><div class="failure-grid"><article class="failure-card"><span>WATCH OUT</span><h3>${escapeHtml(item.failure[0])}</h3><p>${escapeHtml(item.failure[1])}</p></article><article class="failure-card"><span>TRY NEXT</span><h3>${escapeHtml(item.experiment[0])}</h3><p>${escapeHtml(item.experiment[1])}</p></article></div></section><nav class="reader-nav" aria-label="前后单元">${navButton(prev,"← 上一单元")}${navButton(next,"下一单元 →",true)}</nav>`; document.title = `${item.title} · CS224n NLP Lab`; refreshIcons(); }
function renderVisual(item) { const asset = VISUAL_ASSETS[item.viz]; return `<div class="visual-lab"><div class="visual-topline"><span>${escapeHtml(item.visualLabel)}</span><span>gpt-image visual / ${String(item.id).padStart(2,"0")}</span></div><figure class="visual-canvas"><img class="gpt-diagram" src="../assets/cs224n-diagram-${asset}.png" alt="${escapeHtml(item.visualLabel)} 的方向流程图" loading="lazy" /></figure><p class="visual-note"><b>READ THE DIAGRAM</b>　${escapeHtml(item.visualNote)}</p></div>`; }
function renderFormula(item) { const [formula, copy, terms] = item.formula; return `<div class="formula-card"><div class="formula"><small>OBJECTIVE / MECHANISM</small>${escapeHtml(formula)}</div><div class="formula-copy"><p>${escapeHtml(copy)}</p><dl>${terms.map(([term,desc]) => `<div><dt>${escapeHtml(term)}</dt><dd>${escapeHtml(desc)}</dd></div>`).join("")}</dl></div></div>`; }
function renderSVG(kind) {
  const wrap = (body) => `<svg class="viz-svg" viewBox="0 0 720 230" role="img" aria-label="${escapeHtml(kind)} diagram">${body}</svg>`;
  if (kind === "embedding") return wrap(`<line class="stroke" x1="70" y1="190" x2="670" y2="190"/><line class="stroke" x1="120" y1="210" x2="120" y2="25"/><circle class="teal" cx="250" cy="90" r="9"/><circle class="teal" cx="288" cy="113" r="7"/><circle class="teal" cx="226" cy="126" r="6"/><circle class="coral" cx="514" cy="58" r="9"/><circle class="coral" cx="552" cy="81" r="7"/><circle class="coral" cx="531" cy="112" r="6"/><circle class="gold" cx="426" cy="151" r="7"/><path class="edge-teal" d="M260 96 C330 50 410 46 500 60" stroke-dasharray="5 5"/><text x="218" y="74" class="label-strong">semantic cluster A</text><text x="506" y="40" class="label-strong">semantic cluster B</text><text x="418" y="174">ambiguous neighbour</text><text x="76" y="33">dimension 2</text><text x="625" y="211">dimension 1</text>`);
  if (kind === "gradient") return wrap(`<rect class="soft-teal" x="64" y="78" width="120" height="70" rx="9"/><rect class="soft-violet" x="300" y="78" width="120" height="70" rx="9"/><rect class="soft-coral" x="536" y="78" width="120" height="70" rx="9"/><path class="edge-teal" d="M184 113 H300" marker-end="url(#a)"/><path class="edge-teal" d="M420 113 H536" marker-end="url(#a)"/><path class="edge-coral" d="M536 160 H420" stroke-dasharray="5 5"/><path class="edge-coral" d="M300 160 H184" stroke-dasharray="5 5"/><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="currentColor"/></marker></defs><text x="92" y="118" class="label-strong">input x</text><text x="332" y="118" class="label-strong">hidden h</text><text x="572" y="118" class="label-strong">loss L</text><text x="197" y="62">forward activations →</text><text x="232" y="186">← backward gradients</text>`);
  if (kind === "token") return wrap(`<text x="58" y="48" class="label-strong">unhappiness</text><path class="edge-teal" d="M170 43 H246"/><rect class="soft-teal" x="248" y="24" width="100" height="38" rx="7"/><rect class="soft-teal" x="365" y="24" width="100" height="38" rx="7"/><rect class="soft-teal" x="482" y="24" width="100" height="38" rx="7"/><text x="274" y="48" class="label-strong">un</text><text x="383" y="48" class="label-strong">happi</text><text x="501" y="48" class="label-strong">ness</text><path class="stroke" d="M83 145 H642"/><circle class="coral" cx="183" cy="145" r="8"/><circle class="gold" cx="310" cy="145" r="8"/><circle class="teal" cx="437" cy="145" r="8"/><circle class="violet" cx="564" cy="145" r="8"/><text x="84" y="187">string → merges → subwords → IDs</text><text x="155" y="122">training rule boundary</text>`);
  if (kind === "sequence") return wrap(`<text x="74" y="45">x₁</text><text x="221" y="45">x₂</text><text x="368" y="45">x₃</text><text x="515" y="45">x₄</text><rect class="soft-teal" x="52" y="69" width="74" height="58" rx="11"/><rect class="soft-teal" x="199" y="69" width="74" height="58" rx="11"/><rect class="soft-teal" x="346" y="69" width="74" height="58" rx="11"/><rect class="soft-teal" x="493" y="69" width="74" height="58" rx="11"/><text x="77" y="104" class="label-strong">h₁</text><text x="224" y="104" class="label-strong">h₂</text><text x="371" y="104" class="label-strong">h₃</text><text x="518" y="104" class="label-strong">h₄</text><path class="edge-teal" d="M126 98 H199 M273 98 H346 M420 98 H493"/><path class="edge-coral" d="M91 70 V51 M238 70 V51 M385 70 V51 M532 70 V51"/><text x="80" y="176">information must travel through recurrent state</text><path class="edge-coral" d="M106 190 C230 222 420 222 540 190" stroke-dasharray="5 5"/><text x="266" y="219">long-range gradient path</text>`);
  if (kind === "beam") return wrap(`<circle class="teal" cx="70" cy="114" r="11"/><circle class="gold" cx="242" cy="55" r="10"/><circle class="gold" cx="242" cy="114" r="10"/><circle class="gold" cx="242" cy="173" r="10"/><circle class="coral" cx="425" cy="38" r="9"/><circle class="coral" cx="425" cy="86" r="9"/><circle class="coral" cx="425" cy="140" r="9"/><circle class="coral" cx="425" cy="190" r="9"/><path class="edge-teal" d="M82 114 L232 55 M82 114 L232 114 M82 114 L232 173"/><path class="edge-coral" d="M252 55 L416 38 M252 55 L416 86 M252 114 L416 86 M252 114 L416 140 M252 173 L416 140 M252 173 L416 190"/><rect class="soft-violet" x="550" y="61" width="112" height="105" rx="9"/><text x="570" y="92" class="label-strong">keep top B</text><text x="570" y="116">length norm</text><text x="570" y="139">EOS checks</text><text x="52" y="145">BOS</text><text x="198" y="32">candidate prefixes</text>`);
  if (kind === "attention") return wrap(`<text x="52" y="29" class="label-strong">queries</text><text x="490" y="215" class="label-strong">keys</text>${[0,1,2,3,4].map((r)=>[0,1,2,3,4].map((c)=>{const op=[[.1,.18,.7,.25,.12],[.05,.14,.45,.78,.18],[.2,.7,.28,.16,.08],[.65,.25,.15,.1,.05],[.18,.12,.16,.4,.62]][r][c]; return `<rect x="${210+c*49}" y="${41+r*31}" width="38" height="22" rx="3" fill="var(--coral)" opacity="${op}"/>`;}).join("")).join("")}<path class="edge-teal" d="M92 82 C130 40 170 40 206 53"/><path class="edge-teal" d="M92 110 C130 92 170 85 206 84"/><path class="edge-teal" d="M92 138 C130 155 170 155 206 115"/><circle class="teal" cx="76" cy="110" r="15"/><text x="43" y="146">one query</text><text x="254" y="29">attention weights</text>`);
  if (kind === "transformer") return wrap(`<rect class="soft-teal" x="73" y="166" width="230" height="38" rx="7"/><rect class="soft-violet" x="73" y="115" width="230" height="38" rx="7"/><rect class="soft-coral" x="73" y="64" width="230" height="38" rx="7"/><text x="118" y="190" class="label-strong">token + position</text><text x="121" y="139" class="label-strong">multi-head attention</text><text x="117" y="88" class="label-strong">FFN + residual</text><path class="edge-teal" d="M188 166 V153 M188 115 V102"/><path class="edge-coral" d="M318 83 C385 65 430 65 484 85"/><rect class="soft-teal" x="491" y="59" width="150" height="53" rx="7"/><rect class="soft-violet" x="491" y="133" width="150" height="53" rx="7"/><text x="522" y="90" class="label-strong">layer ℓ</text><text x="522" y="164" class="label-strong">layer ℓ+1</text><path class="edge-teal" d="M565 112 V133"/><text x="365" y="216">repeat N times</text>`);
  if (kind === "mask") return wrap(`<rect class="soft-teal" x="64" y="62" width="245" height="116" rx="9"/><rect class="soft-violet" x="410" y="62" width="245" height="116" rx="9"/><text x="111" y="88" class="label-strong">bidirectional mask</text><text x="468" y="88" class="label-strong">causal mask</text>${[0,1,2,3].map((r)=>[0,1,2,3].map((c)=>`<rect x="${91+c*40}" y="${103+r*16}" width="12" height="10" rx="2" fill="var(--teal)" opacity=".8"/>`).join("")).join("")}${[0,1,2,3].map((r)=>[0,1,2,3].map((c)=>`<rect x="${438+c*40}" y="${103+r*16}" width="12" height="10" rx="2" fill="${c<=r ? "var(--violet)" : "var(--line)"}" opacity="${c<=r ? .85 : .45}"/>`).join("")).join("")}<text x="106" y="204">each position sees both sides</text><text x="457" y="204">each position sees only the past</text>`);
  if (kind === "decode") return wrap(`<text x="66" y="38" class="label-strong">raw logits</text><text x="490" y="38" class="label-strong">after temperature + top-p</text>${[44,83,122,163,209].map((h,i)=>`<rect class="${i===2?"coral":"soft-teal"}" x="${74+i*52}" y="${192-h}" width="27" height="${h}" rx="3"/>`).join("")}${[29,59,152,76,0].map((h,i)=>`<rect class="${i===2?"coral":"soft-violet"}" x="${478+i*38}" y="${192-h}" width="23" height="${h}" rx="3" opacity="${h?1:.25}"/>`).join("")}<path class="edge-coral" d="M360 115 H441"/><text x="365" y="103">reshape distribution</text><text x="58" y="215">many possible tokens</text><text x="474" y="215">sample from kept mass</text>`);
  if (kind === "evaluation") return wrap(`<rect class="soft-teal" x="60" y="55" width="145" height="125" rx="9"/><rect class="soft-violet" x="286" y="55" width="145" height="125" rx="9"/><rect class="soft-coral" x="512" y="55" width="145" height="125" rx="9"/><text x="84" y="86" class="label-strong">automatic</text><text x="84" y="110">metric</text><text x="310" y="86" class="label-strong">slice</text><text x="310" y="110">analysis</text><text x="536" y="86" class="label-strong">human</text><text x="536" y="110">judgment</text><path class="edge-teal" d="M205 117 H286 M431 117 H512"/><text x="80" y="210">one score</text><text x="297" y="210">where it fails</text><text x="526" y="210">whether it helps</text>`);
  return wrap(`<circle class="coral" cx="118" cy="114" r="22"/><rect class="soft-teal" x="247" y="76" width="132" height="76" rx="9"/><rect class="soft-violet" x="493" y="76" width="132" height="76" rx="9"/><path class="edge-coral" d="M140 114 H247 M379 114 H493"/><text x="71" y="159">capture</text><text x="279" y="117" class="label-strong">classify</text><text x="524" y="117" class="label-strong">regress</text><path class="edge-teal" d="M553 153 C530 210 232 211 122 143" stroke-dasharray="6 5"/><text x="290" y="210">turn failures into tests</text>`);
}
function navButton(item, label) { return item ? `<button type="button" data-nav="${item.id}"><span>${label}</span><b>${escapeHtml(item.title)}</b></button>` : `<button type="button" disabled></button>`; }
function filteredModules() { return MODULES.filter((item) => { const read = state.read.has(item.id); const matchFilter = state.filter === "all" || (state.filter === "read" ? read : !read); const text = [item.title, item.slug, item.summary, ...item.tags, ...item.lenses.flat()].join(" ").toLowerCase(); return matchFilter && (!state.query || text.includes(state.query)); }); }
function currentModule() { return MODULES.find((item) => item.id === state.current) || MODULES[0]; }
function selectModule(id, scrollMobile) { if (!MODULES.some((item) => item.id === id)) return; state.current = id; localStorage.setItem(KEYS.current, String(id)); renderNav(); renderReader(); if (scrollMobile && window.innerWidth <= 700) els.reader.scrollIntoView({ behavior: "smooth", block: "start" }); }
function move(delta) { selectModule(Math.max(1, Math.min(MODULES.length, state.current + delta)), true); }
function toggleRead(id) { state.read.has(id) ? state.read.delete(id) : state.read.add(id); localStorage.setItem(KEYS.read, JSON.stringify([...state.read])); renderProgress(); renderNav(); renderReader(); }
async function copyCode(button) { const old = button.querySelector("b").textContent; const text = currentModule().code; try { await navigator.clipboard.writeText(text); } catch { const area = document.createElement("textarea"); area.value = text; area.style.cssText = "position:fixed;opacity:0"; document.body.append(area); area.select(); document.execCommand("copy"); area.remove(); } button.querySelector("b").textContent = "已复制"; setTimeout(() => { if (button.isConnected) button.querySelector("b").textContent = old; }, 1400); }
function applyTheme() { const stored = localStorage.getItem(KEYS.theme); const theme = stored || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"); document.documentElement.dataset.theme = theme; els.theme.innerHTML = icon(theme === "dark" ? "sun" : "moon"); }
function safeJson(value) { try { return JSON.parse(value || "null"); } catch { return null; } }
function icon(name) { return `<i data-lucide="${name}"></i>`; }
function escapeHtml(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function refreshIcons() { if (window.lucide) window.lucide.createIcons(); }
boot();
